name: Publish to NPM

on:
  push:
    branches:
    - main
    - release/*

jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: 16
#      - run: npm ci
#      - run: npm test

  publish-npm:
#    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
#      - name: NPM config
#        run: npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
#        env:
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm ci
      - run: npm run build
        name: Build
      - run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
